-- SARAH
-- TH 1:10
-- DAYOFWEEK: 4
-- TIMEOFDAY: AK
-- CODE: 
-- CLASSNAME: HOMESCHOOL (6&UP)
-- MAX: 10
-- AVAILABLE: 10

INSERT INTO classes (CLASS_ID, TEACH, CLASSTIME, DAYOFWEEK, TIMEOFDAY, CLASSNAME, MAX, AVAILABLE, CREA_TMS, UPDT_TMS)
SELECT
    (SELECT MAX(CLASS_ID) FROM classes)+1 AS CLASS_ID,
    'SARAH' AS TEACH,
    'TH 1:10' AS CLASSTIME,
    4 AS DAYOFWEEK,
    'AK' AS TIMEOFDAY,
    'HOMESCHOOL (6&UP)' AS CLASSNAME,
    10 AS MAX,
    10 AS AVAILABLE,
    datetime('now', 'localtime') AS CREA_TMS,
    datetime('now', 'localtime') AS UPDT_TMS
;